Create table STUDENTS
(
    ROLLNO VARCHAR2(5) primary key,
    NAME VARCHAR2(20),
    MARKS NUMBER
);

INSERT INTO STUDENTS VALUES('S001','Rahul',90);
INSERT INTO STUDENTS VALUES('S002','Rohan',45);
INSERT INTO STUDENTS VALUES('S003','Sidhu',35);
INSERT INTO STUDENTS VALUES('S004','Sree',50);