CREATE TABLE STD_HONORS (
    rollno NUMBER PRIMARY KEY,
    name VARCHAR(30),
    s1 NUMBER,
    s2 NUMBER
);

INSERT INTO STD_HONORS VALUES (52, 'Bob', 8,8);
INSERT INTO STD_HONORS VALUES (53, 'Charlie', 9, 4);
INSERT INTO STD_HONORS VALUES (51, 'Alice', 5, 2);
INSERT INTO STD_HONORS VALUES (54, 'David', 65, 70);
INSERT INTO STD_HONORS VALUES (55, 'Eve', 80, 85);
INSERT INTO STD_HONORS VALUES (56, 'Frank', 55, 60);
INSERT INTO STD_HONORS VALUES (57, 'Grace', 7, 8);
INSERT INTO STD_HONORS VALUES (58, 'Hannah', 88, 90);
INSERT INTO STD_HONORS VALUES (59, 'Ivy', 32, 94);
INSERT INTO STD_HONORS VALUES (510, 'Jack', 70, 5);